### PR TITLE
chore(project): upgrade dependencies to latest

### PR DESCRIPTION
**Pull request by cueedee**
@jonahkagan, this PR bumps the [jshint](https://github.com/jshint/jshint/tree/2.9.2) dependency to 2.9.2.

Please consider merging it in and releasing a new version.

### CODE REVIEW

**Comment by jonahkagan** [comment]
@cueedee we're no longer using coffee-jshint at Clever. Would you like to take ownership over the repo/npm package so that you can continue to upgrade it as necessary?

**Comment by cueedee** [comment]
@jonahkagan, sure would like to, but before we proceed; I'm investigating with my employer, marviq, whether they would like to take the ownership instead of just me personally; Would you or Clever mind that idea? I'd still be happy to do it myself though, should either party have any objections.

**Comment by jonahkagan** [comment]
Yep, that would be fine.

**Comment by cueedee** [comment]
Hi @jonahkagan, [marviq](https://github.com/marviq) have indicated their willingness to take the ownership. So we are ready whenever you are.

**Comment by jonahkagan** [comment]
@cueedee awesome! We'll need to know the Github org you want it transferred to (assuming https://github.com/marviq) as well as the npm username who should own the package. I think that should do it.

**Comment by cueedee** [comment]
The GitHub org is https://github.com/marviq indeed. My npm username is `cueedee <org.npmjs.718039.david@distelpluis.nl>`.

**Comment by jonahkagan** [comment]
@cueedee I transferred you ownership of the npm package.

We can't transfer the repo to marviq because we aren't admins of the org. We can only transfer to a user, not an org.

We tried to transfer ownership to you but weren't able to because you already have a fork of it. I see three ways forward:
1. You delete your fork and we transfer the repo to you
2. We delete this repo and your fork becomes the source repo (not sure if this will work)
3. You tell us the username of someone else at marviq and we transfer it to them

Let me know what you want to do!

**Comment by cueedee** [comment]
Understood. I have deleted my fork. Try transfering it to me first. I figure I should be able to transfer it to marviq myself once that's completed.

**Comment by cueedee** [comment]
Guys, @cozmo, I see only now that you've attempted a transfer and I realize I've missed the window of opportunity for accepting it. My apologies; could you please retry?

**Comment by cozmo** [comment]
@cueedee I've re-initiated the transfer. Want to try again?

**Comment by cueedee** [comment]
@cozmo; Thank you! It's done.

**Comment by cueedee** [comment]
Guys, @cozmo, @jonahkagan, I've done the chores. On GitHub, I removed lingering webhooks & services and replaced references to Clever wherever I could find them. On npm, all maintainers @ clever were removed.

Afaict, that should complete it but to be sure, is there anything that you think remains to be done or undone?

In any case, thanks for being cool!

**Comment by jonahkagan** [comment]
Sounds good to me. We'll let you know if we find anything else. Thanks for taking this on!

**Pull request merged**
